name: serverbench-beta
version: 1.0.0
main: io.serverbench.client.spigot.Main
author: serverbench
api-version: 1.21
folia-supported: true
softdepend:
  - Votifier
  - AFKPlus
  - Essentials
  - PlaceholderAPI